mfteam\nbch\generated\models\ProductRequestType:
    properties:
        req:
            expose: true
            access_type: public_method
            serialized_name: req
            accessor:
                getter: getReq
                setter: setReq
            type: mfteam\nbch\generated\models\CreditReportRequestType
