mfteam\nbch\generated\models\ProductReplyType:
    properties:
        pcr:
            expose: true
            access_type: public_method
            serialized_name: pcr
            accessor:
                getter: getPcr
                setter: setPcr
            type: mfteam\nbch\generated\models\PcrReportType
        report:
            expose: true
            access_type: public_method
            serialized_name: report
            accessor:
                getter: getReport
                setter: setReport
            type: mfteam\nbch\generated\models\CreditReportType
        log:
            expose: true
            access_type: public_method
            serialized_name: log
            accessor:
                getter: getLog
                setter: setLog
            type: mfteam\nbch\generated\models\CreditReportLogType
        err:
            expose: true
            access_type: public_method
            serialized_name: err
            accessor:
                getter: getErr
                setter: setErr
            type: array<mfteam\nbch\generated\models\CodeTextType>
            xml_list:
                inline: false
                entry_name: ctErr
                skip_when_empty: true
