mfteam\nbch\generated\models\ProductType:
    properties:
        prequest:
            expose: true
            access_type: public_method
            serialized_name: prequest
            accessor:
                getter: getPrequest
                setter: setPrequest
            type: mfteam\nbch\generated\models\ProductRequestType
        preply:
            expose: true
            access_type: public_method
            serialized_name: preply
            accessor:
                getter: getPreply
                setter: setPreply
            type: mfteam\nbch\generated\models\ProductReplyType
        preply2:
            expose: true
            access_type: public_method
            serialized_name: preply2
            accessor:
                getter: getPreply2
                setter: setPreply2
            type: mfteam\nbch\generated\models\ProductReplyType
