<?php

namespace mfteam\nbch\models;

use yii\helpers\ArrayHelper;

/**
 * Business information is delivered via B2B, Bulk, and Web (Screen/PDF) channels.
 * This information maps to the TUTDF Business (BU) segment.
 * @property-read null|string $businessStatusText
 */
class Business extends BaseItem
{
    /**
     * Сокращенное название ЮЛ.
     * @var string
     */
    public $abbreviatedBusinessName;
    
    /**
     * Полное наименование ЮЛ, включая организационно-правовую форму
     * @var string
     */
    public $businessName;
    
    /**
     * Название ЮЛ на иностранном языке.
     * @var string
     */
    public $businessNameAlt;
    
    /**
     * Название ЮЛ на одном из языков Российской Федерации.
     * @var string
     */
    public $businessNameRF;
    
    /**
     * Статус ЮЛ
     * @var int
     */
    public $businessStatus = 0;
    
    /**
     * Date of the business event; must be supplied when the Business Status is not 0. Valid format: YYYY-MM-DD.
     * @var string
     */
    public $dateOfStatus;
    
    /**
     * Generated by iCRS. Date of the last update of this segment. Valid format: YYYY-MM-DD.
     * @var string
     */
    public $lastUpdatedDt;
    
    /**
     * The number of directors or owners of the business.
     * @var int
     */
    public $numberOfDirectors;
    
    /**
     * The number of permanent or contracted staff.
     * @var int
     */
    public $numberOfEmployees;
    
    /**
     * Фирменное наименование юридического лица
     * @var string
     */
    public $trademark;
    
    /**
     * @return array
     */
    public function rules()
    {
        return array_merge(parent::rules(),
            [
                [
                    [
                        'abbreviatedBusinessName',
                        'businessName',
                        'businessStatus'
                    ], 'required',
                ],
                [
                    [
                        'abbreviatedBusinessName',
                        'trademark'
                    ],
                    'string',
                    'max' => 255,
                ],
                [
                    [
                        'businessName',
                        'businessNameAlt',
                        'businessNameRF'
                    ],
                    'string',
                    'max' => 1020,
                ],
                [
                    'dateOfStatus',
                    'required',
                    'when' => function(Business $model){
                        return $model->businessStatus !== 0;
                    }
                ],
                [
                    [
                        'dateOfStatus',
                        'lastUpdatedDt'
                    ],
                    'date',
                    'format' => 'yyyy-MM-dd'
                ],
                [
                    [
                        'numberOfDirectors',
                        'businessStatus',
                        'numberOfEmployees'
                    ],
                    'integer'
                ],
                [
                    'businessStatus',
                    'in',
                    'range' => array_keys(self::businessStatusList())
                ]
            ]
        );
    }
    
    /**
     * @return string[]
     */
    public static function businessStatusList(): array
    {
        return [
          0 => 'Функционирует',
          1 => 'Не функционирует',
          2 => 'Реструктуризация',
          3 => 'Находится на рассмотрении',
          4 => 'Перерегистрация',
          5 => 'Продажа',
        ];
    }
    
    /**
     * @return string|null
     * @throws \Exception
     */
    public function getBusinessStatusText(): ?string
    {
        return ArrayHelper::getValue(self::businessStatusList(), $this->businessStatus);
    }
}